### ISSUE TITLE
[TASK]Form Viewerをsubmoduleにする

### ISSUE THREAD

**Issue by kanon-k4** [ritscc/ritscc.github.io#4]
# 背景
フォームビューアの修正・バージョンアップの際に、GitHubの管理者であるシステム管理局がプルリク承認するのは面倒。
開発者もシステム管理局ではない上に、様々なバージョンアップがされることが見込まれるので、別のリポジトリで管理することが望まれる。

# 実装要件
- [ ] ritscc直下に別のリポジトリを生成
 - `ritscc/formviewer`が望ましい
- [ ]  `.gitmodules`を作成
 -https:// 形式で記述する必要がある。

**Comment by kanon-k4** [comment]
出来れば別環境で検証を先に行った方が良いかもしれない

**Comment by itanium-R** [comment]
submodule化したとき，submoduleの変更をこちら（呼出元）に適用するのに毎回
```
git submodule foreach git pull origin master
```
しなあかんみたいですが，大丈夫でしょうか．

**Comment by kanon-k4** [comment]
別リポジトリに移行したため、issueをクローズします。
